### ISSUE TITLE
customer_login.ctp uses non-responsive col classes

### ISSUE THREAD

**Issue by RoyKoeleman** [SW-Retail/themes#3]
https://github.com/SW-Retail/themes/blob/fea145e815003c2fd224557946f102340befddb9/theme_relax/template_files/customer_login.ctp#L19

https://github.com/SW-Retail/themes/blob/fea145e815003c2fd224557946f102340befddb9/theme_relax/template_files/customer_login.ctp#L33

Which makes it a 4-col on mobile, which is too small.

**Comment by SW-Retail** [comment]
This is solved now
